application: bytownstats
version: 1
runtime: python
api_version: 1

handlers:

- url: /(google316bd1801e5001cc\.html)
  static_files: google-verification/\1
  upload: google-verification/(.*)

- url: /stylesheets
  static_dir: stylesheets

- url: /jquery
  static_dir: jquery

- url: /.*
  script: bfcstats.py
